name: OoT3DR Nightly Builds

on:
  push:
    branches: [ main ]

jobs:
  build-cia-3dsx:
    runs-on: ubuntu-latest
    container:
      image: phlex/oot3dr-build-tools

    steps:
      - uses: actions/checkout@v2

      - name: Run Build Script
      
        run: |
          chmod +x linux_build_rando.sh
          ./linux_build_rando.sh
          
      - name: Get shorthand commit for release titles.
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV

      - name: Create Pre-release
        uses: ncipollo/release-action@v1.8.3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: "OoT3D_Randomizer.cia,OoT3D_Randomizer.3dsx,cia.png,3dsx.png"
          prerelease: true
          commit: "${{ github.sha }}"
          tag: "Nightly-${SHORT_SHA}"
          name: "Nightly-${SHORT_SHA}"
          body: |
            Please note that these are DEVELOPMENT builds and may not be entirely stable.
            When reporting issues, please mention the six character commit listed in the randomizer menu.
            CIA QR Code:
            ![CIA Download](https://github.com/${{ github.repository }}/releases/download/Nightly-${SHORT_SHA}/cia.png)
            3DSX QR Code:
            ![CIA Download](https://github.com/${{ github.repository }}/releases/download/Nightly-${SHORT_SHA}/3dsx.png)
